language: go
sudo: false
go:
  - tip
install:
  - go get github.com/Masterminds/glide
  - go get github.com/go-playground/overalls
  - go get golang.org/x/tools/cmd/cover
  - go get github.com/mattn/goveralls
  - if ! go get github.com/golang/tools/cmd/cover; then go get golang.org/x/tools/cmd/cover; fi
script:
  - cd src && $GOPATH/bin/glide install
  - go test $($GOPATH/bin/glide novendor)
  - $GOPATH/bin/overalls -project=github.com/jasonlam604/gotest -covermode=count -ignore=.git,vendor -debug
after_success:
  - $GOPATH/bin/goveralls -coverprofile=overalls.coverprofile -service=travis-ci
